# Generated by Django 2.1.11 on 2019-09-27 08:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False, help_text='This is to make sure deletes are not actual deletes')),
                ('active', models.BooleanField(default=True)),
                ('product', models.CharField(max_length=255)),
                ('revenue_stream', models.CharField(max_length=255)),
                ('income_stream', models.CharField(max_length=255)),
                ('date_paid', models.CharField(max_length=255)),
                ('receipt_number', models.CharField(max_length=255, unique=True)),
                ('amount', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
